# Generated by Django 6.0.7 on 2026-08-03 05:23

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
