# Generated by Django 6.0.7 on 2026-08-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_rename_pages_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='site/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
