# Generated by Django 6.0.7 on 2026-08-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_contactmessage_created_at_contactmessage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(default='No message'),
            preserve_default=False,
        ),
    ]
