# Generated by Django 6.0.7 on 2026-08-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_contactmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='location',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], default='header', max_length=20),
        ),
    ]
