# Generated by Django 6.0.7 on 2026-08-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_remove_page_category_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='Page/'),
        ),
    ]
