# Generated by Django 6.0.7 on 2026-08-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_page_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
